Change GroupListing to support mixed content
TileDB-Inc/TileDB-Cloud-API-Spec pull request #300
Opened 2022-01-19 11:39 UTC by anastasop

This is to support mixed content for groups.

I am not very fond of the model GroupEntry where `group` or `asset` maybe empty. However we currently use swagger 2 which does not have good support for polymorphic types (fixed in swagger 3) I am open to suggestions

2022-01-20 14:44 UTC, alekshs approved these changes

2022-01-20 16:50 UTC, anastasop commented
I added the new endpoint for the group browser. @alekshs @antalakas Please have a look.

I added to this PR because i wanted it to be reviewed together with the new GroupListing definition

2022-01-20 17:52 UTC, anastasop commented
Added some more changed based on discussion with @alekshs

2022-01-21 10:56 UTC, alekshs approved these changes

2022-01-21 16:06 UTC, anastasop commented
@alekshs @antalakas I changed the definition of Group path after a discussion with Alex. I think that the PR is now complete and reflects what UI expects from the rest server

2022-01-21 16:11 UTC, alekshs approved these changes
lgtm

2022-01-28 09:32 UTC, anastasop commented
@alekshs @antalakas Added to group attributes `last_accessed` `share_count` `allowed_actions` and the endpoint for batch operation. Please have a look. With these additions i think the group API is complete. It remains to add the share endpoint which will be added after the rest server PR is merged

2022-01-31 09:50 UTC, antalakas commented on openapi-v1.yaml
> +        description: number of unique namespaces this array is shared with
this group is shared with

2022-01-31 10:03 UTC, antalakas requested changes

2022-01-31 10:03 UTC, antalakas commented on openapi-v1.yaml
> +            $ref: '#/definitions/GroupContents'
Should this be `GroupBrowserData`?

2022-01-31 10:03 UTC, antalakas commented on openapi-v1.yaml
> +  GroupContents:
This definition is only used in `public` endpoint. But I also think that public should return `GroupContents` like shared and owned (see next comment)

2022-02-01 09:54 UTC, anastasop commented on openapi-v1.yaml
> +        description: number of unique namespaces this array is shared with
:+1:

2022-02-01 16:50 UTC, anastasop commented
@alekshs @antalakas A new commit to support multiple names for groups. The name moves from the url to the body

2022-02-21 16:04 UTC, anastasop commented
Closing. Superseded by https://github.com/TileDB-Inc/TileDB-Cloud-API-Spec/pull/305

2022-02-21 16:04 UTC, closed without merging